# Docker Compose for ARM64 (분리된 컨테이너)
services:
  # ARM64에서만 실행되는 별도 Qdrant 컨테이너
  qdrant:
    image: qdrant/qdrant:v1.9.3
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__LOG_LEVEL=INFO
      - QDRANT__SERVICE__HTTP_PORT=6333
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  # 메인 GTOne RAG 앱 (ARM64용 - 외부 Qdrant 사용)
  gtrag-dev:
    build:
      context: ../..
      dockerfile: docker/development/Dockerfile.arm64
      args:
        - TARGETARCH=arm64
    ports:
      - "8501:8501"    # Streamlit
      - "18000:18000"  # FastAPI
    env_file: ../../.env
    environment:
      - PYTHONPATH=/app
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=http://172.16.15.112:11434
      - UVICORN_FLAGS=${UVICORN_FLAGS}
    volumes:
      # 개발시 코드 변경사항 실시간 반영
      - ../../api:/app/api
      - ../../ingestion:/app/ingestion
      - ../../embedding:/app/embedding
      - ../../retriever:/app/retriever
      - ../../llm:/app/llm
      - ../../ui:/app/ui
      - ../../.streamlit:/app/.streamlit
      # 데이터 볼륨
      - gtrag_dev_redis:/var/lib/redis
    depends_on:
      qdrant:
        condition: service_healthy
    healthcheck:
      test: |
        curl -f http://localhost:8501/ && 
        curl -f http://localhost:18000/v1/health
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 120s
    restart: unless-stopped

volumes:
  qdrant_data:
    driver: local
  gtrag_dev_redis:
    driver: local

networks:
  default:
    name: gtrag-dev-network